// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTracker.Infrastructure.Persistence;

#nullable disable

namespace TaskTracker.Infrastructure.Migrations
{
    [DbContext(typeof(TaskTrackerDbContext))]
    [Migration("20260816121658_AddCaseInsensitiveTitle")]
    partial class AddCaseInsensitiveTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TaskTracker.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrgencyLevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("IX_TaskItems_Deadline");

                    b.HasIndex("Stage")
                        .HasDatabaseName("IX_TaskItems_Stage");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskItems_Title_Active")
                        .HasFilter("\"IsDeleted\" = 0");

                    b.HasIndex("UrgencyLevelId")
                        .HasDatabaseName("IX_TaskItems_UrgencyLevelId");

                    b.HasIndex("IsDeleted", "DeletedAtUtc")
                        .HasDatabaseName("IX_TaskItems_IsDeleted_DeletedAtUtc");

                    b.ToTable("TaskItems", (string)null);
                });

            modelBuilder.Entity("TaskTracker.Domain.Entities.UrgencyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UrgencyLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Low",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Medium",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "High",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("TaskTracker.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskTracker.Domain.Entities.UrgencyLevel", "UrgencyLevel")
                        .WithMany("TaskItems")
                        .HasForeignKey("UrgencyLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UrgencyLevel");
                });

            modelBuilder.Entity("TaskTracker.Domain.Entities.UrgencyLevel", b =>
                {
                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
